project:
  type: website
  output-dir: docs

website:
  title: "Raphael Palucci Rosa"
  navbar:
    right:
      - text: "ABOUT"
        href: about.qmd
      - icon: github
        href: https://github.com/
      - icon: rss
        href: rBlog.xml
format:
  html:
    theme: 
      light: theme.scss
      dark: dark-theme.scss
    css: styles.css

editor: visual

