project:
  type: website
  output-dir: docs

website:
  title: "Raphael Palucci Rosa"
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    right:
      - icon: github
        href: https://github.com/
      - icon: rss
        href: rBlog.xml
    left: 
      - text: "ABOUT"
        href: about.qmd
      - text: "BLOG"
        href: blog.qmd
      - text: "GUIDES"
        href: guides.qmd
      - text: "PUBLICATIONS"
        href: publications.qmd
      - text: "PROJECTS"
        href: projects.qmd
  
  page-footer: 
    left: "© 2024 Raphael P. Rosa ∙ Made with [Quarto](https://quarto.org/)"
   
    center: 
      - icon: github
        href: https://github.com/
      - icon: linkedin 
        href: https://www.linkedin.com/in/raphael-palucci-rosa-79767579/
   
    right: 
      - text: "Accessibility"
        href: accessibility.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "License"
        href: license.qmd
        
format:
  html:
    theme: 
      light: 
        - assets/light-theme.scss
        - assets/light-theme-fonts.scss
      dark:
        - assets/dark-theme.scss
        - assets/dark-theme-fonts.scss
    css: styles.css

execute: 
  freeze: auto

editor: visual
